# Generated by Django 4.1.8 on 2023-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0003_alter_jobpost_options_alter_jobpost_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="file",
            field=models.FileField(upload_to="Cv"),
        ),
    ]
